// messageTypes.js
export const ACTIONS = {
  CLIENT_LOGIN: 'client-login',
  CLIENT_PUBLIC_KEY: 'client-public-key',
  CLIENT_REGISTER: 'client-register',
  CLIENT_HELLO: 'client-hello',
  CLIENT_SEND: 'client-send',
  CLIENT_BROADCAST: 'client-broadcast',
  CLIENT_LIST_CLIENTS: 'client-list-clients',
  CLIENT_QUIT: 'client-quit',
  QUIT: 'quit',

  ENCRYPTED: 'encrypted',

  GROUP_CREATE: 'cgroupe',
  GROUP_JOIN: 'join',
  GROUP_BROADCAST: 'gbroadcast',
  GROUP_LIST_MEMBERS: 'members',
  GROUP_LIST_MESSAGES: 'msgs',
  GROUP_LIST: 'groups',
  GROUP_LEAVE: 'leave',
  GROUP_INVITE: 'invite',
  GROUP_KICK: 'kick',
  GROUP_BAN: 'ban',
  GROUP_UNBAN: 'unban',
  GROUP_STATS: 'states',
  GROUP_ACTION: 'gactions',

  SERVER_HELLO: 'server-hello',
  SERVER_INIT: 'server-init',
  SERVER_RECEIVED_KEY: 'server-received-key',
  SERVER_FORWARD: 'server-forward',
  SERVER_BROADCAST: 'server-broadcast',
  SERVER_GROUP_BROADCAST: 'server-group-broadcast',
  SERVER_LIST_RESPONSE: 'server-list-response',
  SERVER_GROUP_LIST_MEMBER_RESPONSE: 'server-group-list-member-response',
  SERVER_GROUP_LIST_MESSAGES_RESPONSE: 'server-group-list-messages-response',
  SERVER_GROUP_LIST_RESPONSE: 'server-group-list-response',
  SERVER_GROUP_LIST_EVENTS_RESPONSE: 'server-group-list-events-response',
  SERVER_QUIT_ACK: 'server-quit-ack',
  SERVER_ERROR: 'server-error',
  SERVER_NOTIFY_ME: 'server-error-me',
  SERVER_NOTIFY: 'server-notify',
  SERVER_NOTIFY_GROUP: 'server-notify-group',
  SERVER_NOTIFY_GROUP_ACTION: 'server-notify-group-action',
};
